### ISSUE TITLE
"init" has quite a number of bugs...

### ISSUE THREAD

**Issue by alf5** [tsedio/tsed-cli#232]
version of tsed - 3.20.12
- selecting pnpm will fail many setups due to peer-dependancies. Use npm or yarn.
- selecting "linter + lint on commit" will fail as the project does not do a "git init" or similar
- selecting graphql generates wrong code in "src/config/index.ts" - no comma
- the generated "package.json" file has bad "script" definitions for other than yarn. "npm run tsc" fails, should be just "tsc"
- selecting all (besides "lint on commit" - see above) will fail to "build" with missing typescript declarations. Specifically: @types/inquirer, @types/fs-extra, @types/oidc-provider
- When the above is fixed there are a number of errors that suggest incompatible libs/modules have been installed. I stopped here.

Hope this is not too terse, tried to keep it simple to reproduce.

**Comment by Romakita** [comment]
Hello @alf5 

Thanks for your feedback.

> selecting pnpm will fail many setups due to peer-dependancies. Use npm or yarn.

PNPM is really unstable tool. While NPM and Yarn have a good peerdependencies resolution, PNPM doesn't seems to work as expected. I'm not responsible about this issue. I prefer to remove this option until, there is no people to maintain this feature.

> selecting "linter + lint on commit" will fail as the project does not do a "git init" or similar

Sorry but, it's not a bug. If you select this options, you have to run the git init after. CLI isn't responsible to do that.
But it's not a problem, the project will be correctly generated.

> When the above is fixed there are a number of errors that suggest incompatible libs/modules have been installed. I stopped here.
GraphQL is a bit complicated because, the module compatibility change every month... So, the solution is to not provide this options or fix the graphql version.
 
I'll try to fix the CLI for the graphql option

See you
Romain

**Comment by Romakita** [comment]
Using NPM, husky is ok:
<img width="256" alt="Capture d’écran 2022-05-10 à 06 26 24" src="https://user-images.githubusercontent.com/1763311/167542575-aa9c85d4-8200-4675-8420-edcae8667d1e.png">

**Comment by Romakita** [comment]
Fixed ;)
